-- ArcadiaCorps v12 — auditoría Owner + historial Staff
-- Ejecutar una vez en Supabase > SQL Editor.

create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid not null references auth.users(id) on delete restrict,
  target_user_id uuid references auth.users(id) on delete set null,
  action text not null check (char_length(action) between 2 and 80),
  reason text not null check (char_length(reason) between 5 and 500),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists admin_audit_logs_created_idx on public.admin_audit_logs(created_at desc);
create index if not exists admin_audit_logs_target_idx on public.admin_audit_logs(target_user_id);

create table if not exists public.ticket_audit_logs (
  id bigint generated by default as identity primary key,
  ticket_number bigint not null,
  actor_id uuid not null references auth.users(id) on delete restrict,
  action text not null check (char_length(action) between 2 and 80),
  reason text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists ticket_audit_logs_ticket_idx on public.ticket_audit_logs(ticket_number, created_at desc);

alter table public.admin_audit_logs enable row level security;
alter table public.ticket_audit_logs enable row level security;

-- Función auxiliar. SECURITY DEFINER evita depender de políticas recursivas sobre profiles.
create or replace function public.current_app_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select coalesce((select role from public.profiles where id = auth.uid() and is_active = true), 'user');
$$;

revoke all on function public.current_app_role() from public;
grant execute on function public.current_app_role() to authenticated;

-- Auditoría Owner: solo Owner puede leer e insertar desde el navegador.
drop policy if exists admin_audit_owner_select on public.admin_audit_logs;
create policy admin_audit_owner_select on public.admin_audit_logs
for select to authenticated
using (public.current_app_role() = 'owner');

drop policy if exists admin_audit_owner_insert on public.admin_audit_logs;
create policy admin_audit_owner_insert on public.admin_audit_logs
for insert to authenticated
with check (public.current_app_role() = 'owner' and actor_id = auth.uid());

-- Historial de tickets: staff/owner leen e insertan. Usuarios normales no ven notas de auditoría.
drop policy if exists ticket_audit_staff_select on public.ticket_audit_logs;
create policy ticket_audit_staff_select on public.ticket_audit_logs
for select to authenticated
using (public.current_app_role() in ('staff','owner'));

drop policy if exists ticket_audit_staff_insert on public.ticket_audit_logs;
create policy ticket_audit_staff_insert on public.ticket_audit_logs
for insert to authenticated
with check (public.current_app_role() in ('staff','owner') and actor_id = auth.uid());

grant select, insert on public.admin_audit_logs to authenticated;
grant select, insert on public.ticket_audit_logs to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- Recomendado para que el indicador de mensajes nuevos funcione si las columnas aún no existen.
alter table public.tickets add column if not exists last_sender_role text;

-- Actualiza last_message_at y last_sender_role cuando entra un mensaje.
create or replace function public.sync_ticket_last_message()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare sender_role text;
begin
  select coalesce(role,'user') into sender_role from public.profiles where id = new.sender_id;
  update public.tickets
     set last_message_at = new.created_at,
         last_sender_role = coalesce(sender_role,'user')
   where ticket_number = new.ticket_number;
  return new;
end;
$$;

drop trigger if exists trg_sync_ticket_last_message on public.ticket_messages;
create trigger trg_sync_ticket_last_message
after insert on public.ticket_messages
for each row execute function public.sync_ticket_last_message();

select
  to_regclass('public.admin_audit_logs') as admin_audit_ready,
  to_regclass('public.ticket_audit_logs') as ticket_audit_ready,
  public.current_app_role() as current_role;
