begin;

create table if not exists public.arc_role_audit (
  id bigint generated by default as identity primary key,
  actor_id uuid not null references auth.users(id) on delete restrict,
  target_user_id uuid not null references auth.users(id) on delete cascade,
  old_role text not null check (old_role in ('user','staff','owner')),
  new_role text not null check (new_role in ('user','staff','owner')),
  created_at timestamptz not null default now()
);

create index if not exists arc_role_audit_created_idx on public.arc_role_audit(created_at desc);
alter table public.arc_role_audit enable row level security;

create or replace function public.current_user_role()
returns text
language sql stable security definer
set search_path = public
as $$
  select coalesce((select p.role::text from public.profiles p where p.id = auth.uid()),'user');
$$;

revoke all on function public.current_user_role() from public, anon;
grant execute on function public.current_user_role() to authenticated;

drop policy if exists arc_role_audit_owner_select on public.arc_role_audit;
create policy arc_role_audit_owner_select on public.arc_role_audit
for select to authenticated
using (public.current_user_role() = 'owner');

revoke all on public.arc_role_audit from public, anon, authenticated;
grant select on public.arc_role_audit to authenticated;

create or replace function public.admin_set_user_role(target_user_id uuid,new_role text)
returns public.profiles
language plpgsql security definer
set search_path = public, pg_catalog
as $$
declare
  updated_profile public.profiles;
  old_role_text text;
  role_type_sql text;
begin
  if auth.uid() is null then raise exception 'Sesión no válida'; end if;
  if public.current_user_role() <> 'owner' then raise exception 'No autorizado'; end if;

  new_role := lower(trim(new_role));
  if new_role not in ('owner','staff','user') then raise exception 'Rol no válido'; end if;

  select p.role::text into old_role_text
  from public.profiles p
  where p.id = target_user_id
  for update;

  if old_role_text is null then raise exception 'Perfil no encontrado'; end if;
  if target_user_id = auth.uid() and new_role <> 'owner' then
    raise exception 'No puedes retirar tu propio rol Owner desde este panel';
  end if;

  if old_role_text = new_role then
    select * into updated_profile from public.profiles where id = target_user_id;
    return updated_profile;
  end if;

  select quote_ident(c.udt_schema)||'.'||quote_ident(c.udt_name)
  into role_type_sql
  from information_schema.columns c
  where c.table_schema='public' and c.table_name='profiles' and c.column_name='role';

  if role_type_sql is null then raise exception 'No se pudo detectar el tipo de profiles.role'; end if;

  execute format(
    'update public.profiles set role=$1::%s, updated_at=now() where id=$2 returning *',
    role_type_sql
  )
  using new_role,target_user_id
  into updated_profile;

  insert into public.arc_role_audit(actor_id,target_user_id,old_role,new_role)
  values(auth.uid(),target_user_id,old_role_text,new_role);

  return updated_profile;
end;
$$;

revoke all on function public.admin_set_user_role(uuid,text) from public, anon;
grant execute on function public.admin_set_user_role(uuid,text) to authenticated;

notify pgrst,'reload schema';
commit;

select c.udt_schema,c.udt_name as profiles_role_type,public.current_user_role() as current_role
from information_schema.columns c
where c.table_schema='public' and c.table_name='profiles' and c.column_name='role';
