-- ArcadiaCorps Chat v29: grupos, citas e invitaciones
alter table public.arc_chat_conversations add column if not exists type text not null default 'direct', add column if not exists name text, add column if not exists description text, add column if not exists avatar_path text, add column if not exists owner_id uuid references auth.users(id) on delete set null, add column if not exists invite_code text unique;
alter table public.arc_chat_participants add column if not exists role text not null default 'member';
alter table public.arc_chat_messages add column if not exists reply_to_id uuid references public.arc_chat_messages(id) on delete set null, add column if not exists client_id uuid;
create unique index if not exists arc_chat_messages_client_id_idx on public.arc_chat_messages(client_id) where client_id is not null;
create or replace function public.arc_create_group_chat(group_name text,group_description text,member_ids uuid[],group_avatar_path text default null) returns uuid language plpgsql security definer set search_path=public as $$declare cid uuid; mid uuid;begin if auth.uid() is null then raise exception 'Debes iniciar sesión';end if;if trim(group_name)='' then raise exception 'Nombre requerido';end if;insert into public.arc_chat_conversations(type,name,description,avatar_path,owner_id) values('group',trim(group_name),nullif(trim(group_description),''),group_avatar_path,auth.uid()) returning id into cid;insert into public.arc_chat_participants(conversation_id,user_id,role) values(cid,auth.uid(),'owner');foreach mid in array member_ids loop if mid<>auth.uid() then insert into public.arc_chat_participants(conversation_id,user_id,role) values(cid,mid,'member') on conflict do nothing;end if;end loop;return cid;end$$;
create or replace function public.arc_manage_group_member(cid uuid,target_user uuid,action_name text) returns void language plpgsql security definer set search_path=public as $$declare myrole text;begin select role into myrole from public.arc_chat_participants where conversation_id=cid and user_id=auth.uid();if myrole not in('owner','admin') then raise exception 'Sin permisos';end if;if action_name='remove' then delete from public.arc_chat_participants where conversation_id=cid and user_id=target_user and role<>'owner';elsif action_name='promote' then update public.arc_chat_participants set role='admin' where conversation_id=cid and user_id=target_user and role='member';elsif action_name='demote' then update public.arc_chat_participants set role='member' where conversation_id=cid and user_id=target_user and role='admin';else raise exception 'Acción inválida';end if;end$$;
create or replace function public.arc_leave_group_chat(cid uuid) returns void language plpgsql security definer set search_path=public as $$begin if exists(select 1 from public.arc_chat_conversations where id=cid and owner_id=auth.uid()) then raise exception 'El propietario debe transferir o eliminar el grupo';end if;delete from public.arc_chat_participants where conversation_id=cid and user_id=auth.uid();end$$;
create or replace function public.arc_delete_group_chat(cid uuid) returns void language plpgsql security definer set search_path=public as $$begin delete from public.arc_chat_conversations where id=cid and type='group' and owner_id=auth.uid();if not found then raise exception 'Sin permisos';end if;end$$;
create or replace function public.arc_create_group_invite(cid uuid) returns text language plpgsql security definer set search_path=public as $$declare code text;begin if not public.arc_is_chat_participant(cid) then raise exception 'Sin acceso';end if;code:=substr(encode(gen_random_bytes(12),'hex'),1,16);update public.arc_chat_conversations set invite_code=code where id=cid and type='group';return code;end$$;
create or replace function public.arc_join_group_by_invite(code text) returns uuid language plpgsql security definer set search_path=public as $$declare cid uuid;begin select id into cid from public.arc_chat_conversations where invite_code=code and type='group';if cid is null then raise exception 'Invitación inválida';end if;insert into public.arc_chat_participants(conversation_id,user_id,role) values(cid,auth.uid(),'member') on conflict do nothing;return cid;end$$;
grant execute on function public.arc_create_group_chat(text,text,uuid[],text),public.arc_manage_group_member(uuid,uuid,text),public.arc_leave_group_chat(uuid),public.arc_delete_group_chat(uuid),public.arc_create_group_invite(uuid),public.arc_join_group_by_invite(text) to authenticated;
-- permitir al dueño/admin administrar participantes del grupo
drop policy if exists arc_chat_participants_insert on public.arc_chat_participants;drop policy if exists arc_chat_participants_delete on public.arc_chat_participants;
create policy arc_chat_participants_insert on public.arc_chat_participants for insert to authenticated with check(user_id=auth.uid() or exists(select 1 from public.arc_chat_participants p where p.conversation_id=conversation_id and p.user_id=auth.uid() and p.role in('owner','admin')));
create policy arc_chat_participants_delete on public.arc_chat_participants for delete to authenticated using(user_id=auth.uid() or exists(select 1 from public.arc_chat_participants p where p.conversation_id=conversation_id and p.user_id=auth.uid() and p.role in('owner','admin')));
notify pgrst,'reload schema';
